### ISSUE TITLE
Consistency Check Failed with TensorRT 8.4.3.1

### ISSUE THREAD

**Issue by serser** [thb1314/tensorrt-layernorm-plugin#1]
I've followed instructions to compile `.so` plugin and checked plugin consistency. It seems the result doesn't match and exhibits a big difference (when checked with abs mean).

```
  config.max_workspace_size = 6 << 30
type DataType.HALF
Succeeded building engine!
min, max: -99.6 99.75
nOutput: 1
context.get_binding_shape(nInput + i) (2, 32, 10)
bufferH[-1].dtype:  float16
diff abs max 2.727
diff abs min 0.002129
diff abs mean: 0.867
```
A simple check gives the following,
```
> a[0,0,:]
array([ 0.766,  1.208, -0.529, -1.069,  0.547, -1.021,  1.229,  1.073, -1.335, -0.867],
      dtype=float16)
> bufferH[-1][0,0,:]
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)
```
Could you verify if it is the case at your side?

**Comment by 1049451037** [comment]
Same error here. The output are all zeros. My TensorRT version is 8.5.1

**Comment by thb1314** [comment]
@serser @1049451037 thanks for your attention, I will check this plugin in my TRT environment.

**Comment by 1049451037** [comment]
@serser Hi. I have solved this problem with the help of @thb1314 today. Here is my solution:

* First, you need to compile with correct variables in the `Makefile`, i.e., nvcc path, trt path, sm
* Second, you need to pass tensors with **three** dimensions, and the plugin will normalize over the last dimension
* If you want to support tensors with more or less than three dimensions, you need to modify code [here](https://github.com/thb1314/tensorrt-layernorm-plugin/blob/main/layerNormalizationPlugin.cpp#L95)

Hope it helps, and thanks for tianbin's help!

**Comment by thb1314** [comment]
@serser Furthermore, check the dimension of gamma and beta. In terms of a [B, S, E] shape input tensor (or 4D tensor [B, D1, D2, D3]), the dimension should be equal to E (or D2xD3).

**Comment by serser** [comment]
@1049451037 @thb1314  Thanks guys! My bad, I was using V100 which shall be sm_70. Now it is working. BTW, I see that the latest TensorRT 8.5.2+ has supported [layerNormPlugin](https://github.com/NVIDIA/TensorRT/tree/main/plugin/layerNormPlugin). For compatibility, it would be cool to have various dimensions supported here.

**Comment by 1049451037** [comment]
I find there is a bug of TensorRT LayerNormPlugin https://github.com/NVIDIA/TensorRT/issues/2707. So I use this one... @serser

**Comment by serser** [comment]
> I find there is a bug of TensorRT LayerNormPlugin [NVIDIA/TensorRT#2707](https://github.com/NVIDIA/TensorRT/issues/2707). So I use this one... @serser

There may be some diff, but more or less in 1e-6 as I tried in my project. It would require some digging to look into your case.
